name: reporteria
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - matplotlib
  - seaborn
  - pyodbc
  - sqlalchemy
  - nbformat
  - ipython
  - jinja2
  - beautifulsoup4
  - markdown2
  - openpyxl
